#!/usr/bin/env bash
snakemake -j 160  --latency-wait 1000 --cluster-config cluster.json --cluster "sbatch --partition={cluster.partition} -N {cluster.nodes} --ntasks-per-node {cluster.ntasks} -t {cluster.time}"
